version: "3"
services:
  # postgres:
  #   image: postgres
  #   environment:
  #     POSTGRES_USER: apicurio-registry
  #     POSTGRES_PASSWORD: password
  registry:
    image: quay.io/apicurio/apicurio-registry-mem:latest-snapshot
    ports:
      - 8181:8080
    # environment:
      # QUARKUS_DATASOURCE_URL: 'jdbc:postgresql://postgres/apicurio-registry'
      # QUARKUS_DATASOURCE_USERNAME: apicurio-registry
      # QUARKUS_DATASOURCE_PASSWORD: password
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper